language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python manage.py test users
  - coverage run --source=users manage.py test users
after_success: coveralls
