language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python manage.py collectstatic --no-input
  - python manage.py test users homework
  - coverage run --source=users,homework manage.py test
env:
  - DATABASE_URL='postgres://127.0.0.1:5432/db_teacher2student?user=postgres'
after_success: coveralls
